FROM node:22.12.0-slim

RUN apt-get update -y && apt-get install -y curl && apt-get install -y net-tools && apt-get install -y openssl

WORKDIR /app

COPY package*.json ./

RUN npm install -g npm@11.0.0 && npm install

COPY . .

RUN npx prisma generate

# RUN npm install --save-dev nodemon -g

EXPOSE 8010

CMD ["npm", "run", "dev"]
